name: Deploy to Remote Server

on:
  push:
    branches:
      - master
    paths:
      - 'GenAIPipelineDemoApp/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure all history is fetched

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          # Set variables
          REMOTE_HOST=34.55.19.225
          REMOTE_USER=ubuntu
          REMOTE_PATH=/home/ubuntu

          # Ensure the remote directory exists (create if it doesn't)
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "mkdir -p $REMOTE_PATH"

          # Copy all files and directories to the remote server
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH