name: Deploy to GCS

on:
  push:
    branches:
      - master  # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: your-gcp-project-id  # Required when using auth

      - name: Configure gcloud
        run: |
          gcloud config set compute/region us-central1  # Or your preferred region

      - name: Upload to GCS
        run: |
          gsutil -m cp -r GenAIDemoAppUI/. gs://raapid-ui-bucket/

      - name: Set Content-Type for HTML files
        run: |
          gcloud storage objects update -h "Content-Type:text/html" gs://raapid-ui-bucket/index.html
          gcloud storage objects update -h "Content-Type:text/html" gs://raapid-ui-bucket/workingscreen.html
          gcloud storage objects update -h "Content-Type:text/css" gs://raapid-ui-bucket/markdownstyle.css